// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

interface IERC20 {
    function transferFrom(address from, address to, uint256 amount) external returns (bool);
    function transfer(address to, uint256 amount) external returns (bool);
}

/**
 * @title HedgePayBatch Secured
 * @dev Handles secure bulk distribution of enterprise payroll on the Morph network.
 */
contract HedgePayBatch {
    
    struct PayrollRecord {
        address recipient;
        uint256 tokenAmount;
        string internalDepartment; 
    }

    event PayrollExecuted(address indexed business, bytes32 indexed batchId, uint256 totalDistributed, uint256 totalEmployees);
    event IndividualPayoutLogged(bytes32 indexed batchId, address indexed employee, uint256 amount, string department);

    // Reentrancy lock protection guard
    uint8 private _unlocked = 1;
    modifier nonReentrant() {
        require(_unlocked == 1, "REENTRANCY_GUARD_TRIGGERED");
        _unlocked = 0;
        _;
        _unlocked = 1;
    }

    /**
     * @notice Executes a multi-address batch transfer of stablecoins securely.
     * @param token The address of the stablecoin (e.g., USDC) on Morph.
     * @param batchId A unique tracking identifier generated by the frontend.
     * @param records An array containing addresses, amounts, and tracking metadata.
     * @param totalSum The pre-calculated total sum of tokens asserted by the caller.
     */
    function executeBatchPayroll(
        address token,
        bytes32 batchId,
        PayrollRecord[] calldata records,
        uint256 totalSum
    ) external nonReentrant {
        require(token != address(0), "INVALID_TOKEN_ADDRESS");
        require(records.length > 0, "EMPTY_PAYROLL_DATA");

        uint256 calculatedSum = 0;
        uint256 recordsLength = records.length;

        // Step 1: Calculate and verify total expenditures to prevent manipulation/frontrunning inflation
        for (uint256 i = 0; i < recordsLength; i++) {
            calculatedSum += records[i].tokenAmount;
        }
        require(totalSum == calculatedSum, "SUM_MISMATCH_DETECTION");

        IERC20 stablecoin = IERC20(token);
        
        // Step 2: Safe pull of required capital into contract context
        safeTransferFrom(stablecoin, msg.sender, address(this), totalSum);

        // Step 3: Distribution loop
        for (uint256 i = 0; i < recordsLength; i++) {
            PayrollRecord calldata record = records[i];
            require(record.recipient != address(0), "INVALID_RECIPIENT_ADDRESS");
            require(record.tokenAmount > 0, "INVALID_PAYOUT_AMOUNT");

            // Low-level call handling ensures absolute data verification for non-standard ERC20s
            safeTransfer(stablecoin, record.recipient, record.tokenAmount);

            emit IndividualPayoutLogged(batchId, record.recipient, record.tokenAmount, record.internalDepartment);
        }

        emit PayrollExecuted(msg.sender, batchId, totalSum, recordsLength);
    }

    // Inline SafeERC20 implementation patterns for clean Remix deployment
    function safeTransfer(IERC20 token, address to, uint256 value) internal {
        (bool success, bytes memory data) = address(token).call(
            abi.encodeWithSelector(token.transfer.selector, to, value)
        );
        require(success && (data.length == 0 || abi.decode(data, (bool))), "SAFE_TRANSFER_FAILED");
    }

    function safeTransferFrom(IERC20 token, address from, address to, uint256 value) internal {
        (bool success, bytes memory data) = address(token).call(
            abi.encodeWithSelector(token.transferFrom.selector, from, to, value)
        );
        require(success && (data.length == 0 || abi.decode(data, (bool))), "SAFE_TRANSFER_FROM_FAILED");
    }
}
